version: '2'

services:
  fpm:
    build:
      context: .
      dockerfile: infrastructure/fpm/Dockerfile
    image: millidavids/lumen:fpm
    env_file: .env
    volumes:
      - ./:/var/www/html
  web:
    image: realpage/nginx:1.9
    volumes:
      - ./infrastructure/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  db:
    image: postgres:9.5.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: service_user
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: service_db
  composer:
    image: realpage/builder:composer-1
    volumes_from:
      - fpm